@startuml
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide enum methods

class LauncherKingdomino{
    + {static} main( args:String[] )
}

package Model{
    class Graph {

    }

    class Dominoes {
       -id:Integer
       -firstSuitColor:String
       -secondSuitColor:String
       -crownsFirstSuit:Integer
       -crownsSecondSuit:Integer

       +Dominoes(id:Integer, firstSuitColor:String, secondSuitColor:String,
       crownsFirstSuit:Integer, crownsSecondSuit:Integer)
       +getPosition():
       +setPosition()
    }

    class King{

    }

    class Castle {

    }

    class GameMode{
        +setStrategy()
        +executeStrategy()
    }

    GameMode *-> "-_strategy\n1"GameModeStrategy : > select
    interface GameModeStrategy<<interface>>{
        gameModeStrategy()
    }


    package Mode{
        class Dynasty implements GameModeStrategy{

        }

        class MiddleKingdom implements GameModeStrategy{

        }

        class Harmony implements GameModeStrategy{

        }

        class MightyDuel implements GameModeStrategy{

        }
    }

    class SetUpGame{
        +setStrategyPlayer()
        +executeStrategy()
    }

    interface SetUpGameStrategy<<interface>>{
        +strategyPlayer()
    }

    SetUpGame *-> "-_strategy\n1"SetUpGameStrategy : > launch

    class SetUpDuo implements SetUpGameStrategy
    {

    }

    class SetUp implements SetUpGameStrategy
    {

    }

    class Player {

    }

    enum KingColor {
        +ROSE
        +JAUNE
        +VERT
        +BLEU
    }

}

package View {
    class KingDominoGUI
    {

    }
}

package Controller {
    class ControllerFacade{
        +doKingDomino()
    }
}

LauncherKingdomino ..> ControllerFacade : <<create>> >
ControllerFacade ..> SetUpGame : <<create>>
King *-l-> "1\n- _color" KingColor : has >
Castle *-l-> "1\n- _color" KingColor : has >

@enduml